---

- hosts: 192.168.50.11
  vars:
    - users: "{{ survey_users.split('\n') }}"

  tasks:
  - name: "Create user accounts and add users to groups"
    user:
      name: "{{ item }}"
    with_items: "{{ users }}"

  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
    with_items: "{{ users }}"
