---

- hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: create a new droplet
      digital_ocean_droplet:
        state: present
        name: ansible
        oauth_token: {{ api_token }}
        size: 2gb
        region: fra1
        image: fedora-32-x64
        wait_timeout: 500
      register: my_droplet

    - debug:
        msg: "ID is {{ my_droplet.data.droplet.id }}, IP is {{ my_droplet.data.ip_address }}"
