---
- remote_user: root
  hosts: all
  tasks:
    - name: Create a virtual machine on given ESXi hostname
      vmware_guest:
        hostname: 192.168.0.186
        username: "root"
        password: "Athyde.08"
        validate_certs: no
        folder: /ha-datacenter/vm
        name: ansible-01
        state: poweredoff
        guest_id: rhel8Guest
        # This is hostname of particular ESXi server on which user wants VM to be deployed
        esxi_hostname: "cluster"
        disk:
        - size_gb: 10
          type: thin
          datastore: datastore1
        hardware:
          memory_mb: 512
          num_cpus: 1
          scsi: paravirtual
        networks:
        - name: VM Network
          mac: aa:bb:dd:aa:00:14
          ip: 10.10.10.100
          netmask: 255.255.255.0
          device_type: vmxnet3
        wait_for_ip_address: yes
      delegate_to: localhost
      register: deploy_vm