- hosts: all
  tasks:
    - name: Install Red Hat Access Insights Client
      yum: 
        name: insights-client
        state: latest
      become: yes


    - name: Configure Red Hat Access Insights Client
      template: 
        src: insights-client.conf.j2 
        dest: /etc/insights-client/insights-client.conf
      become: yes

    - name: Register to the Red Hat Access Insights Service
      command: insights-client --register
      become: yes
