---

- hosts: 192.168.50.11
  tasks:
  - name: Remove the user entered by survey
    user:
      name: "{{ username }}"
      state: absent
      remove: yes

  - name: Recursively remove user directory
    file:
      path: "/home/{{ username }}"
      state: absent
