- name: Gather logs files from remote systems
  hosts: 192.168.50.11
  become: yes

  tasks:
  
  - set_fact: 
      timestamp: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"
      
  - name: Ansible create file with content example
    copy:
      dest: "/tmp/{{ timestamp }}.txt"
      content: |
        I am a logfile from.
      
         
  - name: Copy Remote-To-Remote (from serverA to serverB)
    synchronize: 
      src: "/tmp/{{ timestamp }}.txt"
      dest: /tmp/
    delegate_to: "{{ remote_server }}"
    


