- name: Gather logs files from remote systems
  hosts: 192.168.50.11
  become: yes

  tasks:
  - name: Fetch stuff from the remote and save to local
    synchronize:  
      src: {{ item }} 
      dest: /tmp/ 
      mode: pull
    with_items:
      - "var/log"

