- name: Gather logs files from remote systems
  hosts: 192.168.50.11
  become: yes

  tasks:
  
  - set_fact: 
      timestamp: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"
      
  - name: Compress directory /path/to/foo/ into /path/to/foo.tgz
    archive:
      path: /var/log
      dest: "/tmp/{{ timestamp }}.logs.tgz"
      
#   - name: Synchronization using rsync protocol (pull)
#     synchronize:
#       mode: pull
#       src: "/tmp/{{ timestamp }}.logs.tgz"
#       dest: "/tmp/"
         
   - name: Copy Remote-To-Remote (from serverA to serverB)
     synchronize: 
       src: "/tmp/{{ timestamp }}.logs.tgz"
       dest: /tmp/
     delegate_to: 192.168.50.11
    


