---
- name: Publishing our Website
  hosts: 192.168.50.11
  tasks:
  - name: Create websites directory under /home/vagrant/
    file:
      path: /home/vagrant/websites
      state: directory
      owner: vagrant
      group: vagrant
      mode: '0755'
  
  - name: Get Repository
    git:
      repo: "{{ Website-Repository }}"
      dest: "/home/vagrant/websites/sites"
      accept_hostkey: yes

  - name: Copy website to /var/www/html
    copy:
      src: /home/vagrant/websites/sites/website/
      dest: /var/www/html
      remote_src: true 
    become: yes
    
  - name: This will restore /var/www's context as determined by SELinux's system policy to /var/www and all folders and files below it.
    command: restorecon -R /var/www
    become: yes

